# Generated by Django 5.1.4 on 2025-03-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechRescueZoneApp', '0002_category_solutioncategory_conversation_hardware_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
