# Generated by Django 5.1.4 on 2025-03-31 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechRescueZoneApp', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('export', 'Export'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
