# Generated by Django 5.1.4 on 2025-04-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechRescueZoneApp', '0005_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='hardware',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='user',
        ),
        migrations.RemoveField(
            model_name='solutioncomment',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='solutioncomment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='solutionrating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='solutionrating',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='solutionrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='SolutionComment',
        ),
        migrations.DeleteModel(
            name='SolutionRating',
        ),
    ]
