from django.contrib import admin
from .models import *

admin.site.register(Profile)
admin.site.register(Category)
admin.site.register(Hardware)
admin.site.register(HardwareImage)
admin.site.register(HardwareReview)
admin.site.register(Order)
admin.site.register(OrderItem)
admin.site.register(SolutionCategory)
admin.site.register(Solution)
admin.site.register(SolutionStep)
admin.site.register(SolutionImage)
admin.site.register(SolutionComment)
admin.site.register(SolutionRating)
admin.site.register(Conversation)
admin.site.register(Message)
admin.site.register(Notification)
admin.site.register(Payment)
admin.site.register(PaymentMethod)
